version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Kyiv
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
    reviewers: [Baskerville42]
    labels: [dependencies, javascript]
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types: [minor, patch]
      development-minor-and-patch:
        dependency-type: development
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 10
    reviewers: [Baskerville42]
    labels: [dependencies, github-actions]
    groups:
      github-actions:
        patterns: ["*"]
