changelog:
  exclude:
    labels: [skip-changelog]
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Security
      labels: [security]
    - title: Content
      labels: [documentation]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
